spring:
  datasource:
    url: jdbc:h2:file:~/testdb;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

