spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:file:~/tamtam-batchdb;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
