CREATE TABLE IF NOT EXISTS tour_attractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id VARCHAR(30) NOT NULL,
    content_type_id VARCHAR(10) NOT NULL,
    title VARCHAR(300) NOT NULL,
    addr1 VARCHAR(500),
    addr2 VARCHAR(500),
    zipcode VARCHAR(20),
    tel VARCHAR(100),
    first_image VARCHAR(1000),
    first_image2 VARCHAR(1000),
    map_x NUMERIC(18, 14),
    map_y NUMERIC(18, 14),
    mlevel VARCHAR(10),
    area_code VARCHAR(10),
    sigungu_code VARCHAR(10),
    ldong_regn_cd VARCHAR(10),
    ldong_regn_nm VARCHAR(100),
    ldong_signgu_cd VARCHAR(10),
    ldong_signgu_nm VARCHAR(100),
    cat1 VARCHAR(20),
    cat2 VARCHAR(20),
    cat3 VARCHAR(20),
    created_time VARCHAR(30),
    modified_time VARCHAR(30),
    homepage CLOB,
    overview CLOB,
    detail_common_source_modified_time VARCHAR(30),
    detail_common_synced_at TIMESTAMP,
    detail_image_source_modified_time VARCHAR(30),
    detail_image_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tour_attraction_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id VARCHAR(30) NOT NULL,
    image_name VARCHAR(300),
    origin_image_url VARCHAR(1000) NOT NULL,
    small_image_url VARCHAR(1000),
    serial_num VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tour_attractions_content_id
    ON tour_attractions (content_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tour_attraction_images_content_origin
    ON tour_attraction_images (content_id, origin_image_url);

ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS homepage CLOB;
ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS overview CLOB;
ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS detail_common_source_modified_time VARCHAR(30);
ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS detail_common_synced_at TIMESTAMP;
ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS detail_image_source_modified_time VARCHAR(30);
ALTER TABLE tour_attractions ADD COLUMN IF NOT EXISTS detail_image_synced_at TIMESTAMP;
